module.exports = {
    table: 'usertable',
    fieldcount: 10,
    field_len_dist: 'constant',
    fieldlength: 100,
    readallfields: true,
    writeallfields: false,
    readproportion: 0.95,
    updateproportion: 0.05,
    insertproportion: 0.0,
    scanproportion: 0.0,
    readmodifywriteproportion: 0.0,
    requestdistribution: 'uniform',
    maxscanlength: 1000,
    scanlengthdistribution: 'uniform',
    insertorder: 'hashed',
    insertstart: 0,
    recordcount: 'operationcount',
};