[package]
name = "ioheavy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.10.15"
borsh = "0.9.3"
bigint = "4.4.3"
hex = "0.4.3"

[lib]
crate-type = ["cdylib", "lib"]